# Generated by Django 4.2.4 on 2023-09-08 23:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
                ('category', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('IT', 'Information Technology'), ('CN', 'Computer Network'), ('PROGRAMMING', 'Programming'), ('OS', 'Operating Systems'), ('ROBOTICS', 'Robotics'), ('QC', 'Quantum Computing'), ('DS', 'Data Science'), ('AUTOMATION', 'Automation'), ('VR', 'Virtual Reality')], default=None, max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('heading', models.CharField(max_length=120)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='blogs.blog')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
